# docker-compose build
version: "3.8"

services:
  php:
    container_name: php_container
    build: ./docker/php
    volumes:
      - ./:/var/www

  nginx:
    container_name: nginx_container
    image: nginx
    ports:
      - 8020:8000
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
